# Generated by Django 4.2.11 on 2024-08-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='package name')),
                ('type_package', models.CharField(blank=True, choices=[('Civil Status, Online, A3', 'Civil Status, Online, A3'), ('Civil Status, Offline, A3', 'Civil Status, Offline, A3'), ('Civil Status, Online, A4', 'Civil Status, Online, A4'), ('Civil Status, Offline, A4', 'Civil Status, Offline, A4'), ('Administrative Document, Online, A3', 'Administrative Document, Online, A3'), ('Administrative Document, Offline, A3', 'Administrative Document, Offline, A3'), ('Administrative Document, Online, A4', 'Administrative Document, Online, A4'), ('Administrative Document, Offline, A4', 'Administrative Document, Offline, A4'), ('Merge, Online, A3', 'Merge, Online, A3'), ('Merge, Offline, A3', 'Merge, Offline, A3'), ('Merge, Online, A4', 'Merge, Online, A4'), ('Merge, Offline, A4', 'Merge, Offline, A4'), ('Name, Online, A3', 'Name, Online, A3'), ('Name, Offline, A3', 'Name, Offline, A3'), ('Name, Online, A4', 'Name, Online, A4'), ('Name, Offline, A4', 'Name, Offline, A4')], max_length=50, null=True, verbose_name='type package')),
                ('total_votes', models.IntegerField(blank=True, null=True, verbose_name='total votes')),
                ('entered_votes', models.IntegerField(blank=True, null=True, verbose_name='entered votes')),
                ('not_entered_votes', models.IntegerField(blank=True, null=True, verbose_name='not entered votes')),
                ('total_real_votes', models.IntegerField(blank=True, null=True, verbose_name='total real votes')),
                ('total_fields', models.IntegerField(blank=True, null=True, verbose_name='total fields')),
                ('total_merging_votes', models.IntegerField(blank=True, null=True, verbose_name='total merging votes')),
                ('total_erroring_fields', models.IntegerField(blank=True, null=True, verbose_name='total erroring fields')),
                ('processing_check', models.IntegerField(default=0, verbose_name='processing check')),
                ('payment', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Processing', 'Processing')], max_length=30, null=True, verbose_name='payment')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='project name')),
                ('project_description', models.CharField(blank=True, max_length=100, verbose_name='project description')),
                ('code_customer', models.CharField(blank=True, max_length=5, verbose_name='code customer')),
                ('created', models.DateField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Package_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Entering', 'Entering'), ('Error', 'Error')], max_length=12, null=True, verbose_name='insert status')),
                ('check_status', models.CharField(blank=True, choices=[('Completed', 'Completed')], max_length=30, null=True, verbose_name='check status')),
                ('insert_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='package url')),
                ('check_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='package url')),
                ('start_insert', models.DateField(blank=True, null=True, verbose_name='started insert')),
                ('dead_insert', models.DateField(blank=True, null=True, verbose_name='deaded insert')),
                ('finish_insert', models.DateField(blank=True, null=True, verbose_name='finished insert')),
                ('start_check', models.DateField(blank=True, null=True, verbose_name='started check')),
                ('dead_check', models.DateField(blank=True, null=True, verbose_name='deaded check')),
                ('finish_check', models.DateField(blank=True, null=True, verbose_name='finished check')),
                ('note_admin', models.CharField(blank=True, max_length=50, null=True, verbose_name='note admin')),
                ('note_check', models.CharField(blank=True, max_length=50, null=True, verbose_name='note check')),
                ('note_sup', models.CharField(blank=True, max_length=50, null=True, verbose_name='note sup')),
                ('log_sup', models.DateTimeField(blank=True, null=True, verbose_name='log sup')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('inserter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inserter', to=settings.AUTH_USER_MODEL)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.package')),
                ('sup_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_support_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='document path')),
                ('status', models.CharField(blank=True, choices=[('Entered', 'Entered'), ('Completed', 'Completed'), ('Error', 'Error'), ('Not Checked', 'Not Checked'), ('Not Entered', 'Not Entered'), ('Incorrect Entry', 'Incorrect Entry')], max_length=30, null=True, verbose_name='status')),
                ('fields', models.IntegerField(blank=True, null=True, verbose_name='fields')),
                ('errors', models.IntegerField(blank=True, null=True, verbose_name='errors')),
                ('type', models.CharField(blank=True, choices=[('KH', 'KH'), ('KS', 'KS'), ('KT', 'KT'), ('HN', 'HN'), ('CMC', 'CMC')], max_length=4, null=True, verbose_name='type')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_executor', to=settings.AUTH_USER_MODEL)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.package')),
            ],
        ),
    ]
