# Generated by Django 4.2.11 on 2024-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='note_admin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note admin'),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_erroring_fields',
            field=models.IntegerField(blank=True, null=True, verbose_name='total error fields'),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_fields',
            field=models.IntegerField(blank=True, null=True, verbose_name='total fields'),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_merging_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='total merging votes'),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_real_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='total real votes'),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='total votes'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type_package',
            field=models.CharField(blank=True, choices=[('Civil, Online, A3', 'Civil, Online, A3'), ('Civil, Offline, A3', 'Civil, Offline, A3'), ('Civil, Online, A4', 'Civil, Online, A4'), ('Civil, Offline, A4', 'Civil, Offline, A4'), ('VBHC, Online, A3', 'VBHC, Online, A3'), ('VBHC, Offline, A3', 'VBHC, Offline, A3'), ('VBHC, Online, A4', 'VBHC, Online, A4'), ('VBHC, Offline, A4', 'VBHC, Offline, A4'), ('Merging, Online, A3', 'Merging, Online, A3'), ('Merging, Offline, A3', 'Merging, Offline, A3'), ('Merging, Online, A4', 'Merging, Online, A4'), ('Merging, Offline, A4', 'Merging, Offline, A4'), ('Naming, Online, A3', 'Naming, Online, A3'), ('Naming, Offline, A3', 'Naming, Offline, A3'), ('Naming, Online, A4', 'Naming, Online, A4'), ('Naming, Offline, A4', 'Naming, Offline, A4')], max_length=30, null=True, verbose_name='type package'),
        ),
    ]
