# Generated by Django 4.2.11 on 2024-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='entered_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='not_entered_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_real_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='package',
            name='entered_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='entered tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='not_entered_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='not entered tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_real_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='total real tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='total tickets'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type_package',
            field=models.CharField(blank=True, choices=[('Hộ tịch, Online, A3', 'Hộ tịch, Online, A3'), ('Hộ tịch, Offline, A3', 'Hộ tịch, Offline, A3'), ('Hộ tịch, Online, A4', 'Hộ tịch, Online, A4'), ('Hộ tịch, Offline, A4', 'Hộ tịch, Offline, A4'), ('VBHC, Online, A3', 'VBHC, Online, A3'), ('VBHC, Offline, A3', 'VBHC, Offline, A3'), ('VBHC, Online, A4', 'VBHC, Online, A4'), ('VBHC, Offline, A4', 'VBHC, Offline, A4'), ('Ghép, Online, A3', 'Ghép, Online, A3'), ('Ghép, Offline, A3', 'Ghép, Offline, A3'), ('Ghép, Online, A4', 'Ghép, Online, A4'), ('Ghép, Offline, A4', 'Ghép, Offline, A4'), ('Đặt tên, Online, A3', 'Đặt tên, Online, A3'), ('Đặt tên, Offline, A3', 'Đặt tên, Offline, A3'), ('Đặt tên, Online, A4', 'Đặt tên, Online, A4'), ('Đặt tên, Offline, A4', 'Đặt tên, Offline, A4')], max_length=50, null=True, verbose_name='type package'),
        ),
    ]
