# Generated by Django 4.2.11 on 2024-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='entered_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='not_entered_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_merging_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_real_votes',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='package',
            name='entered_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='entered tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='not_entered_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='not entered tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_merging_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='total merging tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_real_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='total real tickets'),
        ),
        migrations.AddField(
            model_name='package',
            name='total_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='total tickets'),
        ),
    ]
