# Generated by Django 4.2.11 on 2024-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_package_note_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_detail',
            name='check_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='check status'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='check_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='package url'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='insert_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='insert status'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='insert_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='package url'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='log_sup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='log sup'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='note_check',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note check'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='note_sup',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note sup'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='status_insert',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status insert'),
        ),
    ]
