# Generated by Django 4.2.11 on 2024-08-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_package_detail_checker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_detail',
            name='status_check',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='status_insert',
        ),
    ]
