# Generated by Django 4.2.11 on 2024-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_package_detail_status_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_detail',
            name='check_status',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='check_url',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='dead_check',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='dead_insert',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='finish_check',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='finish_insert',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='insert_status',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='insert_url',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='log_sup',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='note_check',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='note_sup',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='start_check',
        ),
        migrations.RemoveField(
            model_name='package_detail',
            name='start_insert',
        ),
    ]
