# Generated by Django 4.2.11 on 2024-08-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_remove_package_detail_checker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_detail',
            name='check_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='check status'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='check_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='package url'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_detail_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='dead_check',
            field=models.DateField(blank=True, null=True, verbose_name='deaded check'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='dead_insert',
            field=models.DateField(blank=True, null=True, verbose_name='deaded insert'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='finish_check',
            field=models.DateField(blank=True, null=True, verbose_name='finished check'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='finish_insert',
            field=models.DateField(blank=True, null=True, verbose_name='finished insert'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='insert_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='insert status'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='insert_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='package url'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='inserter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_detail_inserter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='log_sup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='log sup'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='note_check',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note check'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='note_sup',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note sup'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='start_check',
            field=models.DateField(blank=True, null=True, verbose_name='started check'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='start_insert',
            field=models.DateField(blank=True, null=True, verbose_name='started insert'),
        ),
        migrations.AddField(
            model_name='package_detail',
            name='sup_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
