# Generated by Django 4.2.11 on 2024-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_package_detail_check_status_package_detail_check_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_detail',
            name='check_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='check status'),
        ),
        migrations.AlterField(
            model_name='package_detail',
            name='insert_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='insert status'),
        ),
    ]
