# Generated by Django 4.2.11 on 2024-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_package_detail_check_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_detail',
            name='insert_status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Typing', 'Typing'), ('Error', 'Error')], max_length=12, null=True, verbose_name='insert status'),
        ),
    ]
