# Generated by Django 4.2.11 on 2024-08-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_package_entered_votes_and_more'),
        ('project', '0012_alter_package_detail_insert_status'),
    ]

    operations = [
    ]
