# Generated by Django 4.2.11 on 2024-08-10 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('CTV', 'CTV'), ('Manager', 'Manager'), ('Support', 'Support')], max_length=7, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.CharField(blank=True, choices=[('Civil, Online, A3', 'Civil, Online, A3'), ('Civil, Offline, A3', 'Civil, Offline, A3'), ('Civil, Online, A4', 'Civil, Online, A4'), ('Civil, Offline, A4', 'Civil, Offline, A4'), ('VBHC, Online, A3', 'VBHC, Online, A3'), ('VBHC, Offline, A3', 'VBHC, Offline, A3'), ('VBHC, Online, A4', 'VBHC, Online, A4'), ('VBHC, Offline, A4', 'VBHC, Offline, A4'), ('Merging, Online, A3', 'Merging, Online, A3'), ('Merging, Offline, A3', 'Merging, Offline, A3'), ('Merging, Online, A4', 'Merging, Online, A4'), ('Merging, Offline, A4', 'Merging, Offline, A4'), ('Naming, Online, A3', 'Naming, Online, A3'), ('Naming, Offline, A3', 'Naming, Offline, A3'), ('Naming, Online, A4', 'Naming, Online, A4'), ('Naming, Offline, A4', 'Naming, Offline, A4')], max_length=30, null=True, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
