# Generated by Django 4.2.11 on 2024-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='account number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_bank',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='code bank'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='identification'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='identification address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='qualification'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.CharField(blank=True, choices=[('Civil, Online, A3', 'Civil, Online, A3'), ('Civil, Offline, A3', 'Civil, Offline, A3'), ('Civil, Online, A4', 'Civil, Online, A4'), ('Civil, Offline, A4', 'Civil, Offline, A4'), ('VBHC, Online, A3', 'VBHC, Online, A3'), ('VBHC, Offline, A3', 'VBHC, Offline, A3'), ('VBHC, Online, A4', 'VBHC, Online, A4'), ('VBHC, Offline, A4', 'VBHC, Offline, A4'), ('Merging, Online, A3', 'Merging, Online, A3'), ('Merging, Offline, A3', 'Merging, Offline, A3'), ('Merging, Online, A4', 'Merging, Online, A4'), ('Merging, Offline, A4', 'Merging, Offline, A4'), ('Naming, Online, A3', 'Naming, Online, A3'), ('Naming, Offline, A3', 'Naming, Offline, A3'), ('Naming, Online, A4', 'Naming, Online, A4'), ('Naming, Offline, A4', 'Naming, Offline, A4')], max_length=30, null=True, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Working'), ('NA', 'Quit')], max_length=2, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='style',
            field=models.CharField(blank=True, choices=[('AD', 'Admin'), ('CTV', 'CTV'), ('MGR', 'Manager'), ('SP', 'Support')], max_length=3, null=True, verbose_name='style'),
        ),
    ]
