# Generated by Django 4.2.11 on 2024-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
