# Generated by Django 4.2.11 on 2024-08-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_style_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('AD', 'Admin'), ('CTV', 'CTV'), ('MGR', 'Manager'), ('SP', 'Support')], max_length=3, null=True, verbose_name='role'),
        ),
    ]
