# Generated by Django 5.0.6 on 2024-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identification',
            field=models.CharField(blank=True, max_length=15, verbose_name='identification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identification_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='identification address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.CharField(blank=True, max_length=50, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=20, verbose_name='qualification'),
        ),
    ]
