# Generated by Django 5.0.6 on 2024-07-01 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_address_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='birthday'),
        ),
    ]
