# Generated by Django 5.0.6 on 2024-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='account number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=20, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.CharField(blank=True, max_length=20, verbose_name='owner'),
        ),
    ]
