# Generated by Django 5.0.6 on 2024-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_customuser_account_number_customuser_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_bank',
            field=models.CharField(blank=True, max_length=10, verbose_name='code bank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_ctv',
            field=models.CharField(blank=True, max_length=10, verbose_name='code ctv'),
        ),
    ]
