# Generated by Django 5.0.6 on 2024-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_customuser_code_customuser_code_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=10, verbose_name='role'),
        ),
    ]
