# Generated by Django 5.0.6 on 2024-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='row'),
        ),
    ]
