# Generated by Django 4.2.11 on 2024-07-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_phone_no'),
        ('authentication', '0018_customuser_row'),
    ]

    operations = [
    ]
