# Generated by Django 5.0.6 on 2024-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_merge_20240702_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_ctv',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='code ctv'),
        ),
    ]
