# Generated by Django 5.0.6 on 2024-07-30 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_name', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='package name')),
                ('type_package', models.CharField(blank=True, choices=[('Civil, Online, A3', 'Civil, Online, A3'), ('Civil, Offline, A3', 'Civil, Offline, A3'), ('Civil, Online, A4', 'Civil, Online, A4'), ('Civil, Offline, A4', 'Civil, Offline, A4'), ('VBHC, Online, A3', 'VBHC, Online, A3'), ('VBHC, Offline, A3', 'VBHC, Offline, A3'), ('VBHC, Online, A4', 'VBHC, Online, A4'), ('VBHC, Offline, A4', 'VBHC, Offline, A4'), ('Merging, Online, A3', 'Merging, Online, A3'), ('Merging, Offline, A3', 'Merging, Offline, A3'), ('Merging, Online, A4', 'Merging, Online, A4'), ('Merging, Offline, A4', 'Merging, Offline, A4'), ('Naming, Online, A3', 'Naming, Online, A3'), ('Naming, Offline, A3', 'Naming, Offline, A3'), ('Naming, Online, A4', 'Naming, Online, A4'), ('Naming, Offline, A4', 'Naming, Offline, A4')], max_length=30, verbose_name='type package')),
                ('note_admin', models.CharField(blank=True, max_length=50, verbose_name='note admin')),
                ('total_votes', models.IntegerField(blank=True, verbose_name='total votes')),
                ('total_real_votes', models.IntegerField(blank=True, verbose_name='total real votes')),
                ('total_fields', models.IntegerField(blank=True, verbose_name='total fields')),
                ('total_merging_votes', models.IntegerField(blank=True, verbose_name='total merging votes')),
                ('total_erroring_fields', models.IntegerField(blank=True, verbose_name='total error fields')),
                ('processing_check', models.IntegerField(default=0, verbose_name='processing check')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='project name')),
                ('project_description', models.CharField(blank=True, max_length=100, verbose_name='project description')),
                ('code_customer', models.CharField(blank=True, max_length=5, verbose_name='code customer')),
                ('created', models.DateField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_status', models.CharField(blank=True, max_length=10, verbose_name='insert status')),
                ('check_status', models.CharField(blank=True, max_length=10, verbose_name='check status')),
                ('insert_url', models.CharField(blank=True, max_length=100, verbose_name='package url')),
                ('check_url', models.CharField(blank=True, max_length=100, verbose_name='package url')),
                ('start_insert', models.DateField(blank=True, null=True, verbose_name='started insert')),
                ('dead_insert', models.DateField(blank=True, null=True, verbose_name='deaded insert')),
                ('finish_insert', models.DateField(blank=True, null=True, verbose_name='finished insert')),
                ('status_insert', models.CharField(blank=True, max_length=50, verbose_name='status insert')),
                ('start_check', models.DateField(blank=True, null=True, verbose_name='started check')),
                ('dead_check', models.DateField(blank=True, null=True, verbose_name='deaded check')),
                ('finish_check', models.DateField(blank=True, null=True, verbose_name='finished check')),
                ('status_check', models.DateField(blank=True, null=True, verbose_name='status check')),
                ('note_check', models.CharField(blank=True, max_length=50, verbose_name='note check')),
                ('note_sup', models.CharField(blank=True, max_length=50, verbose_name='note sup')),
                ('log_sup', models.DateTimeField(blank=True, verbose_name='log sup')),
                ('checker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker', to=settings.AUTH_USER_MODEL)),
                ('inserter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inserter', to=settings.AUTH_USER_MODEL)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.package')),
                ('sup_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period', models.DateField(blank=True, null=True, verbose_name='payroll period')),
                ('evaluation', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='evaluation')),
                ('basic_salary', models.IntegerField(blank=True, verbose_name='basic salary')),
                ('bonus_fine', models.IntegerField(blank=True, verbose_name='bonus/fine')),
                ('final_salary', models.IntegerField(blank=True, verbose_name='final salary')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='note')),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.package')),
                ('processing_check', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_processing_check', to='home.package')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('total_erroring_fields', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_erroring_fields', to='home.package')),
                ('total_fields', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_fields', to='home.package')),
                ('total_merging_votes', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_merging_votes', to='home.package')),
                ('total_votes', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_votes', to='home.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
