# Generated by Django 4.2.11 on 2024-07-30 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period', models.DateField(blank=True, null=True, verbose_name='payroll period')),
                ('evaluation', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='evaluation')),
                ('basic_salary', models.IntegerField(blank=True, verbose_name='basic salary')),
                ('bonus_fine', models.IntegerField(blank=True, verbose_name='bonus/fine')),
                ('final_salary', models.IntegerField(blank=True, verbose_name='final salary')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='note')),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.package')),
                ('processing_check', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_processing_check', to='project.package')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('total_erroring_fields', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_erroring_fields', to='project.package')),
                ('total_fields', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_fields', to='project.package')),
                ('total_merging_votes', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_merging_votes', to='project.package')),
                ('total_votes', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_votes', to='project.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
