# Generated by Django 4.2.11 on 2024-08-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_package_detail_checker_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='basic_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='basic salary'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus_fine',
            field=models.IntegerField(blank=True, null=True, verbose_name='bonus/fine'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='evaluation',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True, verbose_name='evaluation'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='final_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='final salary'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='processing_check',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_processing_check', to='project.package'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_erroring_fields',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_erroring_fields', to='project.package'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_fields',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_fields', to='project.package'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_merging_votes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_merging_votes', to='project.package'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_votes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_total_votes', to='project.package'),
        ),
    ]
