# Generated by Django 4.2.11 on 2024-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_salary_basic_salary_alter_salary_bonus_fine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True, verbose_name='type'),
        ),
    ]
