# Generated by Django 4.2.11 on 2024-08-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_package_detail_check_status_and_more'),
        ('home', '0004_salary_status_alter_salary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='status',
        ),
        migrations.AddField(
            model_name='salary',
            name='status_check',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_status_check', to='project.package_detail'),
        ),
        migrations.AddField(
            model_name='salary',
            name='status_insert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_status_insert', to='project.package_detail'),
        ),
    ]
