# Generated by Django 4.2.11 on 2024-08-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_package_detail_check_status_and_more'),
        ('home', '0005_remove_salary_status_salary_status_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='status_check',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='status_insert',
        ),
        migrations.AddField(
            model_name='salary',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.package_detail'),
        ),
    ]
